server:
  port: 3200
spring:
  application:
    name: jwks-aggregator-service
  config:
    activate:
      on-profile: default
    import: configserver:http://localhost:8888

---
server:
  port: 3200

spring:
  application:
    name: jwks-aggregator-service
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
